language: python
python:
  - 3.5
branches:
  only:
    - master
    - develop
notifications:
  email: false

dist: trusty
sudo: true

before_install:
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - bash continuous-integration/travis/install.sh

# Install packages
install:
  - export PATH="$HOME/miniconda/miniconda/bin:$PATH"
  - source activate "test-environment$TRAVIS_PYTHON_VERSION"
  - which python
  - conda list

# Run test
script:
  - "coverage run --source=acousticsim setup.py test"

# Calculate coverage
after_success:
  - coveralls

cache:
  directories:
    - $HOME/downloads
    - $HOME/tools
    - $HOME/miniconda
